version: 2.1
jobs:
  build:
    docker:
      - image: 'circleci/node:14.17.0'
    steps:
      - checkout
      - restore_cache:
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run: npm install
      - save_cache:
          key: 'v1-dependencies-{{ checksum "package.json" }}'
          paths:
            - node_modules
      - run: react-scripts build
      - checkout
      - run: 
           name: Test
           command: npm test
      - checkout
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN